/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Decentralized Identity",
  "titleDelimiter": "Frictionless, Secure, and Trustworthy",
  "tagline": "Prevent frauds, optimize processes and drive sustainability,with EarthID’s award-winning decentralized identity and verifiable credentials platform.",
  "favicon": "/img/favicon.ico",
  "url": "https://your-docusaurus-test-site.com",
  "baseUrl": "/",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "/Users/nikcorleone13/Desktop/docs/demo_docs/sidebars.js",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": false,
        "theme": {
          "customCss": "/Users/nikcorleone13/Desktop/docs/demo_docs/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "/img/earthid-logo.png",
    "navbar": {
      "style": "dark",
      "logo": {
        "alt": "My Site Logo",
        "src": "/img/earthid-logo.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "EarthiD SDK"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": null,
          "items": []
        },
        {
          "title": "Useful links ",
          "items": [
            {
              "label": "Home",
              "to": "https://www.myearth.id/"
            },
            {
              "label": "Solutions",
              "to": "https://www.myearth.id/solution/products"
            },
            {
              "label": "Events",
              "to": "https://www.myearth.id/resources/webinars"
            },
            {
              "label": "About",
              "to": "https://www.myearth.id/about/company"
            },
            {
              "label": "Blogs",
              "to": "https://www.myearth.id/resources/blogs"
            }
          ]
        },
        {
          "title": "Connect With Us",
          "items": [
            {
              "label": "Twitter",
              "href": "https://twitter.com/earthid_ssi"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/myearth.id/"
            },
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/channel/UCaRjLyN4I_0UrK3NL4zU1Vg"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/myearthid/"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/myearthid/"
            },
            {
              "label": "Mail",
              "href": "https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&to=future@myearth.id"
            }
          ]
        },
        {
          "title": "Others",
          "items": [
            {
              "label": "Privacy Policy",
              "to": "https://www.myearth.id/privacy"
            },
            {
              "label": "App Download",
              "href": "/"
            }
          ]
        }
      ],
      "logo": {
        "alt": "EarthID",
        "src": "img/earthid-logo.png",
        "href": "https://www.myearth.id/",
        "width": 160,
        "height": 45
      },
      "copyright": "Copyright © All Rights Reserved By EarthId"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
